version: '3.1'

services:

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: db_personas2
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
      MYSQL_ROOT_HOST: localhost
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql

  springboot-docker-container:
    image: springboot-docker-container
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - "8080"
    ports:
      - 8080:8080
    depends_on:
      - mysql

volumes:
  mysql: